# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
right_wheel_hinge_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_wheel_hinge
  pid: {p: 100.0, i: 0.0, d: 0.0}

right_wheel_rotate_position_controller:
  type: effort_controllers/JointVelocityController
  joint: right_wheel_rotate
  pid: {p: 100.0, i: 0.0, d: 0.0}

left_wheel_hinge_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_wheel_hinge
  pid: {p: 100.0, i: 0.0, d: 0.0}

left_wheel_rotate_position_controller:
  type: effort_controllers/JointVelocityController
  joint: left_wheel_rotate
  pid: {p: 100.0, i: 0.0, d: 0.0}

right_wheel_rear_rotate_position_controller:
  type: effort_controllers/JointVelocityController
  joint: right_wheel_rear_rotate
  pid: {p: 100.0, i: 0.0, d: 0.0}

left_wheel_rear_rotate_position_controller:
  type: effort_controllers/JointVelocityController
  joint: left_wheel_rear_rotate
  pid: {p: 100.0, i: 0.0, d: 0.0}


